// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQinsShOZ98qukfEZA6TmS1VayKhESsj8',
    appId: '1:254639569224:web:673c90623c1e8ae40f1b7d',
    messagingSenderId: '254639569224',
    projectId: 'finanzas-2520f',
    authDomain: 'finanzas-2520f.firebaseapp.com',
    storageBucket: 'finanzas-2520f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC130tLd1_DBQDC-SVlaZKvAV_5w2wCZjo',
    appId: '1:254639569224:android:effe8c6e0d1f27590f1b7d',
    messagingSenderId: '254639569224',
    projectId: 'finanzas-2520f',
    storageBucket: 'finanzas-2520f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgpbkeKZQmjtqS-1iUIGxiuEYgxRkL0to',
    appId: '1:254639569224:ios:634f278ef810a7490f1b7d',
    messagingSenderId: '254639569224',
    projectId: 'finanzas-2520f',
    storageBucket: 'finanzas-2520f.appspot.com',
    iosBundleId: 'com.example.firestorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgpbkeKZQmjtqS-1iUIGxiuEYgxRkL0to',
    appId: '1:254639569224:ios:634f278ef810a7490f1b7d',
    messagingSenderId: '254639569224',
    projectId: 'finanzas-2520f',
    storageBucket: 'finanzas-2520f.appspot.com',
    iosBundleId: 'com.example.firestorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQinsShOZ98qukfEZA6TmS1VayKhESsj8',
    appId: '1:254639569224:web:0719c3546c4391b80f1b7d',
    messagingSenderId: '254639569224',
    projectId: 'finanzas-2520f',
    authDomain: 'finanzas-2520f.firebaseapp.com',
    storageBucket: 'finanzas-2520f.appspot.com',
  );

}